# Generated by Django 5.1.7 on 2025-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anel',
            name='forjadoPor',
            field=models.CharField(choices=[('Elfos', 'Elfos'), ('Anões', 'Anões'), ('Homens', 'Homens'), ('Sauron', 'Sauron')], max_length=100),
        ),
    ]
